blank_issues_enabled: true
contact_links:
    - name: ğŸ“œ Code of Conduct
      url: https://github.com/shan-shan-dev/.github/blob/main/CODE_OF_CONDUCT.md
      about: In any way you want to interact with us, you need to abide by the terms of our adopted Code of Conduct.
    - name: ğŸ’¬ Chat
      url: https://discord.gg/PkHEhfV2
      about: Our Discord server is active, come join us!
    - name: â“ Support
      url: https://github.com/orgs/shan-shan-dev/discussions
      about: The issue tracker is not a place for questions. Please use Discussions -> Q&A instead.
